In [58]:
import distcomputing as dists
numAlts = 3
dMatDict = dists.genDistMatrices(numAlts)
import logging as l
logger = l.getLogger()
logger.setLevel("DEBUG")
import numpysimfunsNONuniform as sf


DEBUG:root:RankingSpace as dimensions(13,)
DEBUG:root:rankings is now:
[[1 1 1]
 [1 1 2]
 [1 2 1]
 [1 2 2]
 [1 2 3]
 [1 3 2]
 [2 1 1]
 [2 1 2]
 [2 1 3]
 [2 2 1]
 [2 3 1]
 [3 1 2]
 [3 2 1]]
DEBUG:root:Rank considered is i=1, currentRank (by opinion) is
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]
DEBUG:root:Rank considered is i=2, currentRank (by opinion) is
[[4]
 [3]
 [3]
 [2]
 [2]
 [2]
 [3]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]
DEBUG:root:Rank considered is i=3, currentRank (by opinion) is
[[4]
 [4]
 [4]
 [4]
 [3]
 [3]
 [4]
 [4]
 [3]
 [4]
 [3]
 [3]
 [3]]
DEBUG:root:Dimensions of Row and Col are (13, 1, 3), (1, 13, 3)


Computing KS3 took 0.0 seconds!
Computing DP3 took 0.0 seconds!
Computing CS3 took 0.01 seconds!


In [2]:
sf.deliberate(dist_df=dMatDict["KS"+str(numAlts)], rounds=20, agents=9, reliability=.51, simulations=2, favorOneself = False, dynamicSimEnd = True)

DEBUG:root:Initial rankings: 
[[455 534 527  64 295 101 498 117 267]
 [148 521 139 198 142 463 536  65 243]]
DEBUG:root:Speaking order: 
[[8 2 7 3 1 4 6 5 0]
 [1 5 3 0 6 4 8 2 7]]
DEBUG:root:current :
[[455 534 527  64 295 101 498 117 267]
 [148 521 139 198 142 463 536  65 243]]

DEBUG:root:Announ :
[267 521]

DEBUG:root:num of optimal opins by agent :
[[ 2  4  1  3  3  3 27  3  1]
 [ 7  1 11  5  3  3  9 12  8]]
DEBUG:root:looking at agent(col) 0 with bool-col from [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False 

DEBUG:root:  ->indicestochoosefrom is [258 375 401 477]
DEBUG:root:   -she chooses 375 (zoro = 1)
DEBUG:root:   -she chooses 401 (zoro = 1)
DEBUG:root:   -she chooses 401 (zoro = 0)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False

DEBUG:root:looking at agent(col) 3 with bool-col from [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False Fal

DEBUG:root:  ->indicestochoosefrom is [ 72  76 136]
DEBUG:root:   -she chooses 72 (zoro = 0)
DEBUG:root:   -she chooses 136 (zoro = 1)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False  Tr

DEBUG:root:looking at agent(col) 6 with bool-col from [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False  True False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False Fal

DEBUG:root:  ->indicestochoosefrom is [ 17  24 218 224 399 401 509]
DEBUG:root:   -she chooses 17 (zoro = 0)
DEBUG:root:   -she chooses 218 (zoro = 1)
DEBUG:root:   -she chooses 218 (zoro = 0)
DEBUG:root:   -she chooses 218 (zoro = 0)
DEBUG:root:   -she chooses 401 (zoro = 1)
DEBUG:root:   -she chooses 401 (zoro = 0)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False Fa

DEBUG:root:looking at agent(col) 9 with bool-col from [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False Fal

DEBUG:root:  ->indicestochoosefrom is [199 383 503]
DEBUG:root:   -she chooses 199 (zoro = 0)
DEBUG:root:   -she chooses 199 (zoro = 0)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False Fa

DEBUG:root:looking at agent(col) 12 with bool-col from [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True False False False False Fa

DEBUG:root:  ->indicestochoosefrom is [ 24 166 179 193 194 195 316 317 319 330 338 442]
DEBUG:root:   -she chooses 166 (zoro = 1)
DEBUG:root:   -she chooses 179 (zoro = 1)
DEBUG:root:   -she chooses 193 (zoro = 1)
DEBUG:root:   -she chooses 194 (zoro = 1)
DEBUG:root:   -she chooses 195 (zoro = 1)
DEBUG:root:   -she chooses 316 (zoro = 1)
DEBUG:root:   -she chooses 317 (zoro = 1)
DEBUG:root:   -she chooses 319 (zoro = 1)
DEBUG:root:   -she chooses 330 (zoro = 1)
DEBUG:root:   -she chooses 330 (zoro = 0)
DEBUG:root:   -she chooses 330 (zoro = 0)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False Fa

DEBUG:root:   =>optOpins is 
[[[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 ...

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ...  True False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]] 
DEBUG:root:newOpin :
[[190 401 376  54 254 136 502 111 267]
 [401 521 532 337 199 517 539 330 462]]

DEBUG:root:optimal opins by agent :
[[[ nan  nan  nan ...  nan  nan  nan]
  [ nan  nan  nan ...  nan  nan  nan]]

 [[ nan  nan  nan ...  nan  nan  nan]
  [ nan  nan  nan ...  nan  nan  nan]]

 [[ nan  nan  nan ...  nan  nan  nan]
  [ nan  nan  nan ...  nan  nan  nan]]

 ...

 [[ nan  nan  nan ...  nan  nan  nan]
  [ nan  

DEBUG:root:  ->indicestochoosefrom is [218 375]
DEBUG:root:   -she chooses 218 (zoro = 0)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False


DEBUG:root:looking at agent(col) 3 with bool-col from [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False Fal

DEBUG:root:  ->indicestochoosefrom is [ 50 118 262]
DEBUG:root:   -she chooses 118 (zoro = 1)
DEBUG:root:   -she chooses 262 (zoro = 1)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False Fa

DEBUG:root:looking at agent(col) 6 with bool-col from [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False Fal

DEBUG:root:  ->indicestochoosefrom is [324 455 527]
DEBUG:root:   -she chooses 455 (zoro = 1)
DEBUG:root:   -she chooses 455 (zoro = 0)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False Fa

DEBUG:root:looking at agent(col) 9 with bool-col from [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False Fal

DEBUG:root:  ->indicestochoosefrom is [166 170 327 328 453]
DEBUG:root:   -she chooses 166 (zoro = 0)
DEBUG:root:   -she chooses 327 (zoro = 1)
DEBUG:root:   -she chooses 328 (zoro = 1)
DEBUG:root:   -she chooses 328 (zoro = 0)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False F

DEBUG:root:looking at agent(col) 12 with bool-col from [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False Fa

DEBUG:root:  ->indicestochoosefrom is [302 523]
DEBUG:root:   -she chooses 523 (zoro = 1)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False


DEBUG:root:looking at agent(col) 1 with bool-col from [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False Fal

DEBUG:root:  ->indicestochoosefrom is [337 446 454]
DEBUG:root:   -she chooses 446 (zoro = 1)
DEBUG:root:   -she chooses 454 (zoro = 1)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False Fa

DEBUG:root:looking at agent(col) 4 with bool-col from [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False Fal

DEBUG:root:  ->indicestochoosefrom is [301 351 517 524]
DEBUG:root:   -she chooses 301 (zoro = 0)
DEBUG:root:   -she chooses 301 (zoro = 0)
DEBUG:root:   -she chooses 524 (zoro = 1)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False

DEBUG:root:   =>optOpins is 
[[[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 ...

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]] 
DEBUG:root:newOpin :
[[218 218 218 109 267 267 401 259 218]
 [454 439 520 451 521 518 524 520 434]]

DEBUG:root:optimal opins by agent :
[[[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 ...

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ..

DEBUG:root:  ->indicestochoosefrom is [259 260]
DEBUG:root:   -she chooses 260 (zoro = 1)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False


DEBUG:root:looking at agent(col) 3 with bool-col from [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False Fal

DEBUG:root:  ->indicestochoosefrom is [ 66 260]
DEBUG:root:   -she chooses 260 (zoro = 1)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False


DEBUG:root:looking at agent(col) 6 with bool-col from [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False Fal

DEBUG:root:  ->indicestochoosefrom is [446 453]
DEBUG:root:   -she chooses 453 (zoro = 1)
DEBUG:root:thus her op2chfrom is: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False


DEBUG:root:   =>optOpins is 
[[[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 ...

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]] 
DEBUG:root:newOpin :
[[291 260 291  49 260 260 291 291 291]
 [450 520 520 520 522 520 438 520 520]]

DEBUG:root:optimal opins by agent :
[[[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 ...

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ..

DEBUG:root:   =>optOpins is 
[[[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 ...

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]] 
DEBUG:root:newOpin :
[[291 260 291 260 260 260 291 291 291]
 [450 450 450 450 522 450 520 450 450]]

DEBUG:root:optimal opins by agent :
[[[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 ...

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ..

DEBUG:root:newOpin :
[[291 260 291 260 260 260 291 291 291]
 [450 450 450 450 450 450 520 450 450]]

DEBUG:root:optimal opins by agent :
[[[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 ...

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]]
DEBUG:root:current :
[[291 260 291 260 260 260 291 291 291]
 [450 450 450 450 450 450 520 450 450]]

DEBUG:root:Announ :
[291 450]

DEBUG:root:num of optimal opins by agent :
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]
DEBUG:root:   =>optOpins is 
[[[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False Fal

DEBUG:root:current :
[[291 260 291 260 260 260 291 291 291]
 [450 450 450 450 450 450 520 450 450]]

DEBUG:root:Announ :
[291 450]

DEBUG:root:num of optimal opins by agent :
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]
DEBUG:root:   =>optOpins is 
[[[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 ...

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]] 
DEBUG:root:newOpin :
[[291 260 291 260 260 260 291 291 291]
 [450 450 450 450 450 450 520 450 450]]

DEBUG:root:optimal opins by agent :
[[[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[

Round 1 of 20 completed. This round took 0.37 seconds
Round 2 of 20 completed. This round took 0.11 seconds


DEBUG:root:current :
[[291 260 291 260 260 260 291 291 291]
 [450 450 450 450 450 450 520 450 450]]

DEBUG:root:Announ :
[291 450]

DEBUG:root:num of optimal opins by agent :
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]
DEBUG:root:   =>optOpins is 
[[[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 ...

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]] 
DEBUG:root:newOpin :
[[291 260 291 260 260 260 291 291 291]
 [450 450 450 450 450 450 520 450 450]]

DEBUG:root:optimal opins by agent :
[[[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[

DEBUG:root:num of optimal opins by agent :
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]
DEBUG:root:   =>optOpins is 
[[[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 ...

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]]] 
DEBUG:root:newOpin :
[[291 260 291 260 260 260 291 291 291]
 [450 450 450 450 450 450 520 450 450]]

DEBUG:root:optimal opins by agent :
[[[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 ..

DEBUG:root:newOpin :
[[291 260 291 260 260 260 291 291 291]
 [450 450 450 450 450 450 520 450 450]]

DEBUG:root:optimal opins by agent :
[[[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 ...

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]]


Round 3 of 20 completed. This round took 0.12 seconds
Round 4 of 20 completed. This round took 0.11 seconds
Deliberation got boring in round 3 
Thus, there are 5 int Matrices in Rankings (one is initial rankings, the rest are updated opinions).


array([[[455, 534, 527,  64, 295, 101, 498, 117, 267],
        [148, 521, 139, 198, 142, 463, 536,  65, 243]],

       [[291, 260, 291, 260, 260, 260, 291, 291, 291],
        [450, 450, 450, 450, 522, 450, 520, 450, 450]],

       [[291, 260, 291, 260, 260, 260, 291, 291, 291],
        [450, 450, 450, 450, 450, 450, 520, 450, 450]],

       [[291, 260, 291, 260, 260, 260, 291, 291, 291],
        [450, 450, 450, 450, 450, 450, 520, 450, 450]],

       [[291, 260, 291, 260, 260, 260, 291, 291, 291],
        [450, 450, 450, 450, 450, 450, 520, 450, 450]]], dtype=int64)

In [7]:
dMat.iloc[[455, 534, 527,  64, 295, 101, 498, 117, 267]].index

Index(['30412', '42310', '41302', '01234', '14203', '02143', '32140', '02341',
       '12403'],
      dtype='object')

In [3]:
dMat = dMatDict["KS5"]
dMat.iloc[[536, 487], [536, 487]]

43021  32021
43021      0      1
32021      1      0

In [4]:
dMat

00000  00001  00010  00011  00012  00021  00100  00101  00102  00110  \
00000      0      4      4      6      7      7      4      6      7      6   
00001      4      0      8      4      3      5      8      4      3     10   
00010      4      8      0      4      5      3      8     10     11      4   
00011      6      4      4      0      1      1     10      8      7      8   
00012      7      3      5      1      0      2     11      7      6      9   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
43021     10     12     10     12     13     11     14     16     15     14   
43102     10     10     14     14     13     15     12     12     11     16   
43120     10     14     10     14     15     13     12     16     17     12   
43201     10     12     14     16     15     17     10     12     13     14   
43210     10     14     12     16     17     15     10     14     15     12   

       ...  42103  42130  42301  42310  43012  43021  43102  43120  43201  \
00000  ...     10     10     10     10     10     10     10     10     10   
00001  ...      8     14     12     14     10     12     10     14     12   
00010  ...     14      8     14     12     12     10     14     10     14   
00011  ...     12     12     16     16     12     12     14     14     16   
00012  ...     11     13     15     17     11     13     13     15     15   
...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
43021  ...      6      4      8      6      2      0      4      2      6   
43102  ...      2      8      4      6      2      4      0      6      2   
43120  ...      8      2      6      4      4      2      6      0      4   
43201  ...      4      6      2      4      4      6      2      4      0   
43210  ...      6      4      4      2      6      4      4      2      2   

       43210  
00000     10  
00001     14  
00010     12  
00011     16  
00012     17  
...      ...  
43021      4  
43102      4  
43120      2  
43201      2  
43210      0  

[541 rows x 541 columns]

In [13]:
(5==3+2==5)

True

In [8]:
file = "sdflkl.a"
file[file.find(".")-1]

'l'

In [5]:
import pickle
with open("W5N51.pkl", "rb") as f:
    Res = pickle.load(f)["KS5"][51]
Res.shape

(5, 1000, 51)

In [6]:
k = 5
Three = Res[0,0,k:3+k]
print(Three)
dMat.iloc[Three].index

[528 452 459]


Index(['41320', '30241', '31020'], dtype='object')

In [17]:
import numpy as np
import logging as l
import pandas as pd
l.debug("Numpysimfuns with debug-messages")
def deliberate(dist_df, rounds, agents, reliability, simulations, favorOneself = False, dynamicSimEnd=True):
    """This function runs the desired number of deliberations all at once using nd-arrays where n >= 3.
    Inputs: 
            - dist_df: a DataFrame giving the distances for all pairs of possible opinions
            - rounds: the number of deliberative rounds, i.e., times each agent is to speak up.
            - agents: the number of agents
            - reliability: the float-reliability that everyone attaches to themselves.
            - simulations: the number of Simulations that are to be run at once.
    """
    import time as t
    # I was tempted to have the agents announce their actual opinions. Instead, they will voice the INDEX of their opinions. 
    # The derivation is kind of lengthy but it works quickly.
    isStrict = [int(max(list(i)))==len(i)-1 for i in  dist_df.columns]
    arr = (dist_df.loc[isStrict, isStrict].index)
    Rankings = np.random.choice(a= arr.shape[0], size=((simulations*agents)))
    Rankings = arr[Rankings]
    Op2Int = pd.DataFrame(dict(zip(dist_df.index, range(dist_df.shape[0]))), index = ["OpinIntegers"]).T
    Rankings = np.array(Op2Int.loc[Rankings].values.reshape(1,simulations, agents))    # ...computation of new round results
    current = Rankings.copy().reshape(simulations, agents)
    l.debug(f"Initial rankings: \n{current}")
    # Now deliberate:
    for rnum in range(rounds): 
        startTime = t.time()
        # First fix speaking order for THIS round but all simulations at once.
        # It is a matrix where a 5 at position ij means that in simulation i, agent 5 is the j'th to speak.
        order = np.array([np.random.choice(agents, (agents,), replace = False) for i in range(simulations)])
        helper = np.repeat(np.arange(agents).reshape(1,-1), simulations, axis=0)
        l.debug(f"Speaking order: \n{order}")
        # The helper-array is an array of stacked aranges which will be used to provide a bool-matrix.
        # This works because using '==' on a matrix and a vector will produce row-wise evaluated bool-rows.
        # The bool-matrix will be used to index into the current opinions.
        # Now, everyone gets to speak her opinion, the others update.
        for step in range(agents): # each round is made of agents [int] steps, because everyone gets to speak their mind once (and only once).
            if step==0==rnum: updateStart = t.time()    
            announcement = current[helper == order[:,step].reshape(-1,1)]
            current = update(current, announcement, dist_df, simulations, agents, reliability, favorOneself)
            if step==0==rnum: print("First Update took", round(t.time()-updateStart), "seconds")
        print(f"Round {rnum+1} of {rounds} completed. This round took {round(t.time()-startTime,2)} seconds", end="\n")
        Rankings = np.concatenate([Rankings, current.reshape(1, simulations, agents)], axis = 0)
        if rnum > 0 and dynamicSimEnd:
            last2roundsnochanges = ((Rankings[-1] == Rankings[-2] )& (Rankings[-1] == Rankings[-3])).all().all()
            if last2roundsnochanges: 
                print("Deliberation got boring in round", rnum, "\nThus, there are", Rankings.shape[0], "int Matrices in Rankings (one is initial rankings, the rest are updated opinions).")
                break
    return Rankings

DEBUG:root:Numpysimfuns with debug-messages


In [122]:
def update(current, announcement,dist_df, simulations, agents, rel, favorOneself = False):
    """This function computes the new opinions of all agents given their old opinions and an announcement.
    Doing this for all sims at once means that current is an intMatrix and announcement is an intVector.
    The outputis an intMatrix of updated opinions.
    -dist_df: a DataFrame holding the distances of all permissible opinions (weak or strict).
    -current: intMatrix of opinion INDICES
    -simulations, agents: int
    -rel: float
    """
    # 0) make sure all inputs are of expected shape:
    assert current.shape == (simulations, agents), "intMatrix current came in unexpected shape!"
    assert announcement.shape == (simulations,) , f"announcement came in unexpected shape ({announcement.shape} instead of {(simulations,)})!"
    assert type(simulations) == int and type(agents) == int and type(rel) == float, "sim, agents or rel came in unexpected datatype, should be int, int, float."
    
    # 1) get some useful variables: helper holds all opinion-indices as an r3A. 
    numOpins = dist_df.shape[0]
    helper3d = np.repeat(np.repeat(np.arange(numOpins).reshape(-1,1,1), current.shape[0], axis = 1 ), current.shape[1], axis = 2  ) 
    # 2) get distances of all potential opinions from announcement and current opinion
    # 2.1 dFromAnnoun
    dFromAnnoun = np.array(dist_df.iloc[announcement].values.T.reshape(-1,simulations,1)).astype(np.float)
    # 2.2 dFromOp
    f = lambda n,dist_df,current,simulations: np.array(dist_df.iloc[current[:,n]].values.T.reshape(-1,simulations,1))
        # Next line gets us a Datacube where for all agents in all simulations each "floor" holds the distance between a potential new opinion and the current one.
    dFromOp = np.concatenate([f(n, dist_df, current, simulations) for n in range(agents)], axis=2).astype(np.float)
    # 3) calculate score-r3A
    score = np.sqrt(rel * dFromOp**2 + (1-rel) * dFromAnnoun**2) # NB: dFromAnnoun is getting broadcasted here!
    # 4) get all optimal opinions for everyone in every simulation
    if favorOneself: # Deducts from own opinion a minusule but tie-breaking amount if we want to favour ourselves.
        score[helper3d==current] = (score[helper3d==current]-(1E-5)) #This amount should be sufficiently small that the own opinion doesn't get preferred if it is not among the truly optimal.
    optOpins = score == np.min(score, axis = 0) # Gives a bool-array True whenever an opinion is optimal.
    l.debug(f"OptOpins (shape {optOpins.shape}): {optOpins}")
    # Maybe, multiple opinions are optimal. Then we need to decide on one. To save computing power, we do (somewhat complicated) slicing and reshaping and only draw random numbers for the agents that have no unique best choice!
    nonuniques = OO[(optOpins.sum(0) > 1).reshape(-1)]
    l.debug(f"nonuniques (shape {nonuniques.shape}): \n{nonuniques}")
    # 5) Assign randomly uniform values to the non-unique optimal opinions, if they exist.
    if nonuniques.shape[0] >0:
        OO = optOpins.reshape(optOpins.shape[0], -1).T
        l.debug(f"rows should hold the heights now: \n{OO}")
        ChoiceScore = np.random.uniform(0,1, (nonuniques.shape))
        uOO = ChoiceScore == (ChoiceScore*nonuniques).max(1).reshape(-1,1)
        OO[(optOpins.sum(0) > 1).reshape(-1)] = uOO # Attention, this assignment CHANGES optOpins!!!
    l.debug(f"optOpins now has shape {optOpins.shape} (as before), but for every agent per simulation holds a unique 'True' (This statement is {(optOpins.sum(0)==1).all().all()})")
    Choice = optOpins * helper3d # Multiplies a bool-array that is True at the unique (but possibly random) choice with the array holding al opinion-indices
    newOpin = Choice.max(axis=0) # Choice is 0 everywhere other than at the unique choices, there it holds the opinion-index. Reducing with max gives the array in convenient form. 
    assert newOpin.shape ==(simulations, agents), f"new Opinion has shape {newOpin.shape}"
    l.debug("current :\n"+ str(current) +"\n")
    l.debug("Announ :\n"+ str(announcement)+"\n")
    l.debug("newOpin :\n"+ str(newOpin)+"\n")
    l.debug(f"score (shape {score.shape}) of agents 0&1 in simulation 0:\n"+ str(score[:,0,:2]))
    l.debug("num of optimal opins by agent :\n"+ str((optOpins.sum(axis=0))))
    optOpins = optOpins.astype(np.float16)
    optOpins[optOpins==0] = np.nan
    l.debug("optimal opins by agent :\n"+ str((optOpins* helper3d)))
    return newOpin

In [123]:
deliberate(dMatDict["KS3"], 2,5,.51,2)

DEBUG:root:Initial rankings: 
[[12 11 11 10 12]
 [ 5  5 12 11  4]]
DEBUG:root:Speaking order: 
[[4 3 1 0 2]
 [0 3 2 4 1]]
DEBUG:root:OptOpins: [[[False False False False False]
  [False False False  True False]]

 [[False False False False False]
  [False False False  True False]]

 [[False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False  True]]

 [[False False False False False]
  [False False False False False]]

 [[False False False False False]
  [ True  True False False False]]

 [[False  True  True False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]]

 [[False False False  True False]
  [False False False  True False]]

 [[False False False False False]
  [False False  True False False]]

 [[False False False False False]
  [False False False False False]]

 [[ True False Fa

DEBUG:root:nonuniques (shape (0, 13)): 
[]
DEBUG:root:optOpins now has shape (13, 2, 5) (as before), but for every agent per simulation holds a unique 'True' (This statement is True)
DEBUG:root:current :
[[12 12 12  9 12]
 [ 3  3  5  1  4]]

DEBUG:root:Announ :
[12  5]

DEBUG:root:newOpin :
[[12 12 12  9 12]
 [ 3  3  5  4  3]]

DEBUG:root:score (shape (13, 2, 5)) of agents 0&1 in simulation 0:
[[3. 3.]
 [5. 5.]
 [3. 3.]
 [5. 5.]
 [6. 6.]
 [4. 4.]
 [1. 1.]
 [3. 3.]
 [4. 4.]
 [1. 1.]
 [2. 2.]
 [2. 2.]
 [0. 0.]]
DEBUG:root:num of optimal opins by agent :
[[1 1 1 1 1]
 [1 1 1 1 1]]
DEBUG:root:optimal opins by agent :
[[[nan nan nan nan nan]
  [nan nan nan nan nan]]

 [[nan nan nan nan nan]
  [nan nan nan nan nan]]

 [[nan nan nan nan nan]
  [nan nan nan nan nan]]

 [[nan nan nan nan nan]
  [ 3.  3. nan nan  3.]]

 [[nan nan nan nan nan]
  [nan nan nan  4. nan]]

 [[nan nan nan nan nan]
  [nan nan  5. nan nan]]

 [[nan nan nan nan nan]
  [nan nan nan nan nan]]

 [[nan nan nan nan nan]
  [na

DEBUG:root:rows should hold the heights now: 
[[False False False False False False False False False False False False
   True]
 [False False False False False False False False False False False False
   True]
 [False False False False False False False False False False False False
   True]
 [False False False False False False False False False  True False False
  False]
 [False False False False False False False False False False False False
   True]
 [False False False  True False False False False False False False False
  False]
 [False False False  True False False False False False False False False
  False]
 [False False False False False  True False False False False False False
  False]
 [False False False False  True False False False False False False False
  False]
 [False False False  True False False False False False False False False
  False]]
DEBUG:root:nonuniques (shape (0, 13)): 
[]
DEBUG:root:optOpins now has shape (13, 2, 5) (as before), but for every agent pe

DEBUG:root:OptOpins: [[[False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]]

 [[False False False False False]
  [ True  True  True False  True]]

 [[False False False False False]
  [False False False  True False]]

 [[False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]]

 [[False False False  True False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]]

 [[ True  True  True False  True]
  [False False False False False]]]
DEBUG:root:rows should hold the heights now: 
[[False False False Fal

First Update took 0 seconds
Round 1 of 2 completed. This round took 0.06 seconds
Round 2 of 2 completed. This round took 0.06 seconds


array([[[12, 11, 11, 10, 12],
        [ 5,  5, 12, 11,  4]],

       [[12, 12, 12,  9, 12],
        [ 3,  3,  5,  4,  3]],

       [[12, 12, 12,  9, 12],
        [ 3,  3,  3,  4,  3]]], dtype=int64)

In [113]:
optOpins = np.random.randint(0,2, (4,2,7))==1
optOpins

array([[[ True, False, False, False,  True,  True,  True],
        [ True,  True, False,  True,  True,  True, False]],

       [[False,  True, False,  True, False,  True, False],
        [False,  True,  True,  True, False, False,  True]],

       [[ True,  True,  True, False,  True,  True, False],
        [ True,  True,  True,  True, False, False, False]],

       [[ True, False, False, False,  True,  True,  True],
        [False,  True,  True,  True,  True,  True, False]]])

In [114]:
OO = optOpins.reshape(optOpins.shape[0], -1).T
l.debug(f"rows should hold the heights now: \n{OO}")
nuOO = OO[(optOpins.sum(0) > 1).reshape(-1)]
l.debug(f"nuOO (shape {nuOO.shape}): \n{nuOO}")
# 5) Assign randomly uniform values to the non-unique optimal opinions, if they exist.
if nuOO.shape[0] >0:
    ChoiceScore = np.random.uniform(0,1, (nuOO.shape))
    uOO = ChoiceScore == (ChoiceScore*nuOO).max(1).reshape(-1,1)
OO[(optOpins.sum(0) > 1).reshape(-1)] = uOO

DEBUG:root:rows should hold the heights now: 
[[ True False  True  True]
 [False  True  True False]
 [False False  True False]
 [False  True False False]
 [ True False  True  True]
 [ True  True  True  True]
 [ True False False  True]
 [ True False  True False]
 [ True  True  True  True]
 [False  True  True  True]
 [ True  True  True  True]
 [ True False False  True]
 [ True False False  True]
 [False  True False False]]
DEBUG:root:nuOO (shape (11, 4)): 
[[ True False  True  True]
 [False  True  True False]
 [ True False  True  True]
 [ True  True  True  True]
 [ True False False  True]
 [ True False  True False]
 [ True  True  True  True]
 [False  True  True  True]
 [ True  True  True  True]
 [ True False False  True]
 [ True False False  True]]


In [116]:
# 5) Assign randomly uniform values to the non-unique optimal opinions, if they exist.
if nuOO.shape[0] >0:
    ChoiceScore = np.random.uniform(0,1, (nuOO.shape))
    uOO = ChoiceScore == (ChoiceScore*nuOO).max(1).reshape(-1,1)
OO[(optOpins.sum(0) > 1).reshape(-1)] = uOO

uOO.shape, "\n", uOO

((11, 4),
 '\n',
 array([[False, False, False,  True],
        [False, False,  True, False],
        [ True, False, False, False],
        [ True, False, False, False],
        [False, False, False,  True],
        [False, False,  True, False],
        [ True, False, False, False],
        [False, False,  True, False],
        [False,  True, False, False],
        [ True, False, False, False],
        [ True, False, False, False]]))

In [117]:
print(optOpins)
OO[(optOpins.sum(0) > 1).reshape(-1)] = uOO
optOpins

[[[ True False False False  True  True  True]
  [ True  True False  True  True  True False]]

 [[False  True False  True False  True False]
  [False  True  True  True False False  True]]

 [[ True  True  True False  True  True False]
  [ True  True  True  True False False False]]

 [[ True False False False  True  True  True]
  [False  True  True  True  True  True False]]]


array([[[False, False, False, False,  True,  True, False],
        [False,  True, False, False,  True,  True, False]],

       [[False, False, False,  True, False, False, False],
        [False, False, False,  True, False, False,  True]],

       [[False,  True,  True, False, False, False, False],
        [ True, False,  True, False, False, False, False]],

       [[ True, False, False, False, False, False,  True],
        [False, False, False, False, False, False, False]]])

In [74]:
np.prod(arr.shape)

12

In [126]:
dMatDict["CS3"]

000  001  010  011  012  021  100  101  102  110  120  201  210
000    0    2    2    2    2    2    2    2    2    2    2    2    2
001    2    0    3    2    1    3    3    2    1    4    4    3    4
010    2    3    0    2    3    1    3    4    4    2    1    4    3
011    2    2    2    0    1    1    4    3    3    3    3    4    4
012    2    1    3    1    0    2    4    3    2    4    4    4    4
021    2    3    1    1    2    0    4    4    4    3    2    4    4
100    2    3    3    4    4    4    0    2    3    2    3    1    1
101    2    2    4    3    3    4    2    0    1    3    4    1    3
102    2    1    4    3    2    4    3    1    0    4    4    2    4
110    2    4    2    3    4    3    2    3    4    0    1    3    1
120    2    4    1    3    4    2    3    4    4    1    0    4    2
201    2    3    4    4    4    4    1    1    2    3    4    0    2
210    2    4    3    4    4    4    1    3    4    1    2    2    0